### ISSUE TITLE
Main To-Do list

### ISSUE THREAD

**Issue by alexandru-dinu** [expman/expman#6]
- [x] add metadata-header to binary / large files
    - describes how the file was generated ([ref](https://codereview.stackexchange.com/q/263622))
- [ ] follow-up: come-up with a fail-proof naming scheme
- [ ] [Idiomatic algebraic data types in Python with dataclasses and Union](http://blog.ezyang.com/2020/10/idiomatic-algebraic-data-types-in-python-with-dataclasses-and-union)
- [ ] "one-size-fits-all" logging
- [ ] maybe monad for handling computation that may fail
- [ ] consistent `argparse`
- [ ] [FileType objects](https://docs.python.org/3/library/argparse.html#filetype-objects)
- [ ] ensuring paths exists
- [ ] static analysis -- catch most of the possible runtime errors
- [ ] simplify working with data splits (train / test) - ensure that we never evaluate on train
- [ ] collect logs (as metadata?) from each stage that produces them
- [ ] mypy best practices
- [ ] "contents" hint for large data structures -- something that complements e.g. `Dict[str, Dict[...]]`
- [ ] `pip install --editable` to bypass copying to `site-packages` -- allows making changes and use the latest version when importing.
